### ISSUE TITLE
program closes whean i press enter on the f3 page 

### ISSUE THREAD

**Issue by 323c** [schismtracker/schismtracker#434] opened 2024-05-13 08:04 UTC
program closes whean i press enter on the f3 page im on windows 11 on the newest version
cpu: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz

gpu: intel intergreted graphics

8 gb ram ddr4

does it every time

**Comment by mrpapersonic** [comment] 2024-05-14 19:47
This was fixed in the newest release, I just forgot to update the website :')

**Closed as not planned by mrpapersonic** 2024-05-14 19:47 UTC
Labels: bug, windows

**Comment by sagamusix** [comment] 2024-05-14 21:09
@mrpapersonic this still seems reproducible on the 20240503 release here.

**Comment by mrpapersonic** [comment] 2024-05-14 21:11
turns out the version I had on my windows machine was from master, not the release. It's fixed now anyway, I'll pull a new release soon™
