### ISSUE TITLE
macOS: color changes after resize

### ISSUE THREAD

**Issue by guaka** [schismtracker/schismtracker#195] opened 2019-06-13 14:54 UTC
Thanks for working on schism, and the new release! https://github.com/schismtracker/schismtracker/releases/tag/issue-175.0

The colors change after resizing on macOS 10.14.5:

![image](https://user-images.githubusercontent.com/54728/59442851-ed0a7b80-8df2-11e9-9e34-2132f49617e9.png)

Before resizing it looks fine:
![image](https://user-images.githubusercontent.com/54728/59442880-fbf12e00-8df2-11e9-9d6e-8e477e20af91.png)

The colors also turn blueish when going full screen.  They're fine again when leaving full screen.

(Note that it's an improvement of the previous version I tried, which had much funkier effects: full screen was simply completely greyish.)

**Comment by jangler** [comment] 2019-06-14 18:24
Looks like a dupe of #168. Do the other video drivers work OK for you? If YUV is reproducibly better then it could be set to default for macOS, as asbjornu suggested.

**Comment by asbjornu** [comment] 2019-08-22 21:05
Well, YUV and OpenGL both preserve the right colors when the window is resized, but as none of them has antialiasing, everything looks very jagged when the size is increased and if you don't keep the aspect ratio, the text will become distorted beyond readable if you stretch it long enough. SDL works much better in these scenarios, minus having its colors messed up.

**Comment by jangler** [comment] 2022-08-07 10:51
Pretty sure this was fixed by 869c01e, since #301 was. Feel free to reopen if not.

**Closed as completed by jangler** 2022-08-07 10:51 UTC

**Comment by asbjornu** [comment] 2022-08-07 13:13
@jangler, yep. I just tested the [20220807 release](https://github.com/schismtracker/schismtracker/releases/tag/20220807) and resizing now works fine on macOS Big Sur 11.6.8.
