### ISSUE TITLE
Crash when playing with Midi ports

### ISSUE THREAD

**Issue by HybridDog** [schismtracker/schismtracker#51] opened 2016-09-29 19:39 UTC
When l try to set the second port in the midi configuration, where it shows Disabled, to output, schismtracker crashes.
There's the gdb backtrace:
http://paste.ubuntu.com/23252596/

**Comment by jangler** [comment] 2016-09-29 20:48
Can reproduce; will look into this.

**Comment by jangler** [comment] 2016-12-19 00:06
Can no longer reproduce…? But #64 can.

**Comment by vcaputo** [comment] 2017-06-15 19:46
@jangler why not just change the assert() to a warning logging the values asserted against, then simply returning prior to scribbling beyond qlen.

Is it unreasonable to expect schism to continue functioning correctly in this state?

logging when this happens may also help?
https://github.com/schismtracker/schismtracker/blob/master/schism/midi-core.c#L641

**Comment by jangler** [comment] 2017-06-15 20:39
I'm thinking this is just a bug that happens when qlen == 0. I haven't looked at the MIDI code in *that* much detail but we might just need another case for that.

**Comment by vcaputo** [comment] 2017-06-15 21:25
Hmm... so the implicit hypothesis is that in something of a low-latency configuration where `audio_buffer_samples` is too small for the midi queue to get established the existing code falls over?

@HybridDog if you can still reproduce this, can you supply a screenshot of the message log viewer page from the environment this occurs in?  (Crtl-F11)  That should help confirm the hypothesis.

**Comment by vcaputo** [comment] 2017-06-16 02:08
@jangler I was able to reproduce the crash, and a fix is waiting in https://github.com/schismtracker/schismtracker/pull/85

**Comment by HybridDog** [comment] 2017-06-16 07:18
l can still reproduce this, but l don't know what you mean by message log viewer.

**Comment by vcaputo** [comment] 2017-06-16 07:36
@HybridDog In schism tracker, if you press Ctrl-F11 it will go to the message log viewer page, which should show some statistics about the audio buffer...

However, I've managed to reproduce the problem myself and already posted a fix in #85.  If you're up for testing that PR and verifying it fixes your problem as well it'd be great!

Thanks

**Comment by vcaputo** [comment] 2017-06-16 21:26
@jangler BTW reproduction proved to be fairly easy here on a plain Debian x86_64 w/ALSA setup.  I just started playing an .it file, and while it was playing went to the MIDI settings and cycled through disabled->input->output on the second entry in the list of ports.  That may prove helpful in testing a fix like #85.

**Comment by jangler** [comment] 2017-06-18 23:23
Just reproduced it by accident. :) I'll take a look at that PR.

**Comment by esaruoho** [comment] 2018-01-07 12:41
are ya guys still seeing this crash? i don't use multiple midiports so not sure how to accomplish this crash :)

**Comment by jangler** [comment] 2018-01-07 14:31
If I open Schism, mess with enabling/disabling MIDI ports, and play a module, it crashes. Likewise, if I open Schism, play a module, and mess with enabling/disabling MIDI ports, it also crashes.

**Comment by jangler** [comment] 2018-01-07 14:33
I have six ports by default on Linux; one for port-0 and five for multicast/IP.

**Comment by esaruoho** [comment] 2018-01-07 14:46
yeah, going crazy enabling and disabling will eventually crash on macOS too.
![schismtrackercrasher](https://user-images.githubusercontent.com/4966687/34650455-5157f5c8-f3ca-11e7-8df1-9be4e5f12e2b.gif)

**Comment by vcaputo** [comment] 2018-01-07 16:06
When I last poked at this issue, all the crashes we were observing were due to the assert at
https://github.com/schismtracker/schismtracker/blob/20170910/schism/midi-core.c#L767

From what I recall, the changes in https://github.com/schismtracker/schismtracker/pull/85/commits/bdc0bdd87aee987c16f9c82f9ddec51d6f6a31d8 fix a fairly obvious mistake in the size calculation of 10ms worth of audio buffers in a given sound setup.

Even with that size calculation fix merged, some setups legitimately have too little buffer space to satisfy the assert.  Those were able to be worked around by fussing directly with the config file to increase the buffer size.  Which I assumed could be done automatically, making schism just bump the output buffer if it's too small when MIDI initializes or something, so we can then remove the assert() and eliminate this crash.  But considering the trivial buffer size commit never landed, I stopped looking at the issues.

It's unclear to me if you guys are tripping over the same assert here or not.  @esaruoho, if you repro your crashes from launching schism in a terminal, I imagine you'd see if the assert is printing anything.

**Comment by esaruoho** [comment] 2018-01-07 16:16
yeah @vcaputo I tested it under macOS Terminal and got this:
```
Assertion failed: (((unsigned)pos) < ((unsigned)qlen)), function midi_send_buffer, file ../schism/midi-core.c, line 767.
Abort trap: 6
```

**Comment by esaruoho** [comment] 2018-01-07 16:25
@vcaputo so.. you're talking about #85 that never landed - which _might_ fix some of the issues with the midicrashing. what I could I guess do, is test #85 and build from that. let's see.
actually, i'm not clever enough to know how to pull this Pull from a non-schismtracker-repo and compile it - if you could help me try it out, i'd try it out and see if mad-switching of midichannels would help or not.

**Comment by vcaputo** [comment] 2018-01-07 16:43
@esaruoho Correct, that PR contains a trivial fix for the buffer size calculation.

It's unclear to me why you have to do mad-switching to trigger the assert though, that sounds like there may be another bug.

If you'd like to try testing that PR there are numerous guides online, such as:
https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-to-Test-a-Pull-Request

**Comment by vcaputo** [comment] 2018-01-07 17:28
@jangler this issue should probably stay open until we get to where that assert never triggers...

**Comment by esaruoho** [comment] 2018-01-07 17:53
yay, i'm no longer able to kill schism by mad-switching between midi inputs, outputs and duplex. pretty neat. thanks for the fix, @vcaputo and @jangler for pushing it in.

**Comment by esaruoho** [comment] 2018-01-07 17:54
@HybridDog can you try it out and see if it crashes for you?

**Comment by vcaputo** [comment] 2018-01-07 19:37
Neat!

**Comment by HybridDog** [comment] 2018-01-07 19:45
When I try to set one of the `Multicast/IP MIDI` to `output`, I get this assertion:
```schismtracker: ../schism/midi-core.c:763: midi_send_buffer: Assertion `((unsigned)pos) < ((unsigned)qlen)' failed.```
Ctrl+F11 tells Buffer size: 512 samples. For any reason this buffer size value is half of the one in the config file.
If I set it to 2048 in the config file, in schismtracker (ctrl+F11) it shows 1024 and I don't get an assertion crash.
(See also https://github.com/schismtracker/schismtracker/pull/85#issuecomment-310460435 (before))

**Comment by esaruoho** [comment] 2018-01-07 19:46
for me on macOS High Sierra, Ctrl+F11 tells Buffer size: 1024 samples. I haven't set any of it in config files.
I'm not sure where to see the files. But, no crashes.

**Comment by HybridDog** [comment] 2018-01-07 19:48
The config file is in ~/.schism/config. Why do I get halved buffer size?

**Comment by vcaputo** [comment] 2018-01-07 19:52
@HybridDog I dunno, haven't looked at that part (and busy with a home improvement project atm).  But a shot in the dark guess would be maybe the config field uses a different unit (e.g. bytes) than what the Ctrl+F11 displays (samples).

**Comment by esaruoho** [comment] 2018-01-07 20:49
Weirdly enough `~/.schism/config` isn't where I can find the Schism configs. 

It's actually at `~/Library/Application Support/Schism Tracker/config` - wherein the Buffer Size is

`buffer_size=1024` - so the exact same as the 1024 buffer size in CTRL-F11.

Also @jangler what does `midi_like_tracker=0` mean? :)

**Comment by jangler** [comment] 2018-01-07 20:53
You can toggle it on the System Configuration (Ctrl-F1) screen. Don't know exactly what it does; it doesn't seem to be documented anywhere.

**Comment by mrpapersonic** [comment] 2024-04-29 21:41
> When I try to set one of the `Multicast/IP MIDI` to `output`, I get this assertion: `` schismtracker: ../schism/midi-core.c:763: midi_send_buffer: Assertion `((unsigned)pos) < ((unsigned)qlen)' failed. `` Ctrl+F11 tells Buffer size: 512 samples. For any reason this buffer size value is half of the one in the config file. If I set it to 2048 in the config file, in schismtracker (ctrl+F11) it shows 1024 and I don't get an assertion crash. (See also [#85 (comment)](https://github.com/schismtracker/schismtracker/pull/85#issuecomment-310460435) (before))

okay, so the reason for this is quite stupid: schism didn't have enough space to create a MIDI queue, nope'd out, set the queue length to zero and it tripped that assert.

I've replaced the assert with an if statement and added code to warn the user in the log about the nonfunctional midi, so this can be closed now.

**Closed as completed by mrpapersonic** 2024-04-29 21:41 UTC
Labels: bug
