### ISSUE TITLE
Mouse cursor outline and envelope cursor

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#484] opened 2024-06-27 23:41 UTC
In IT the mouse cursor has a thin outline, and a smaller cursor for click-dragging instrument envelopes. Neither are present in Schism, but would help cursor visibility. 
https://github.com/schismtracker/schismtracker/assets/151794548/ceb6b070-e895-4f10-8160-8eb2f50a9aac

Lumping these two together because they're about cursor appearance.

**Comment by hotgar** [comment] 2024-07-27 09:05
I've managed to make the cursor look more similar to the IT one. In the IT case it seems like the body of the pointer always has the foreground color and the outline has the background one rather than getting colors from XORing. But its rendering over some parts of the UI is still a bit weird. Not sure how much better than the current one this is.

https://github.com/user-attachments/assets/2f15a9c0-f382-4d84-bd8a-1b254773ebc8


Haven't touched the envelope editor crosshair yet.

**Comment by mrpapersonic** [comment] 2024-07-27 10:41
It's possible (likely even) that some foreground colors are completely wrong. See `draw_text_len` in `schism/vgamem.c`, more particularly the `draw_fill_chars` call which just shoves the same color in both slots. This isn't the full story though, because the scanner checks for the character value set with `draw_fill_chars` and sets the foreground to 3, which may or may not also just be plain wrong ;)

**Comment by hotgar** [comment] 2024-07-27 15:47
Yes, it looks like the rendering oddities are caused by 

https://github.com/schismtracker/schismtracker/blob/e444afa0da227c4b114768a779e7c4cc3992a6d0/schism/vgamem.c#L285-L286

which seems to be there exactly to deal with the `draw_fill_chars` taking only one color and setting both fg and bg to it.

So i guess adding a parameter to the `draw_fill_chars` and maybe setting something like  `DEFAULT_FG 3` in `vgamem.h` would be the solution here.

I've also noticed that this issue doesn't happen with strings that are slurped from an xm module like instrument or sample names because they seem to be padded. So padding the strings could also work but that seems more like a crutch to me.

**Comment by mrpapersonic** [comment] 2024-08-09 22:25
The PR attached to this issue was merged, but github didn't see that :/

**Closed as completed by mrpapersonic** 2024-08-09 22:25 UTC
Labels: bug
