### ISSUE TITLE
Schism 20231029 Playback Issues

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#397] opened 2024-01-17 19:52 UTC
Over the past few months of using Schism 20231029 (Windows build), I've encountered a few playback issues that were not present in Schism 20230906.
Attached below is a .zip file with three modules within, each with its own problem not present in 20230906 on back. As this is specific to Schism 20231029, I've decided to lump these together into one report.

[examples.zip](https://github.com/schismtracker/schismtracker/files/13967088/examples.zip)

In wb22-wk21.it, the Duplicate Sample Check condition on Instrument 11 is ignored both in playback and the instrument list.
- Open wb22-wk21.it in Schism 20231029
- Press F4 to enter Instruments List
- Play Instrument 11
- Play Instrument 12 afterwards
Instruments 11 and 12 both use the same sample, Instrument 11 has a Duplicate Sample Check that should cut the instrument once 12 plays. 
In Schism 20231029 Instrument 11 is **not** cut and continues to play. This can be experienced in playback as well by listening to pattern order 3/16 into 4/16.
In Schism 20230906 the instruments behave as expected, and Instrument 11 is cut once 12 starts to play both in the Instrument List and during playback.

In winter_time_ii.xm, it appears Note-offs are being ignored.
- Open winter_time_ii.xm in Schism 20231029
- Press F5 to play the module
- Arrive at pattern order 4/37
- Listen to either channel 3 or 8 as it crosses over into 5/37
In Schism 20231029 the Note-offs at the start of 5/37 (and throughout the rest of the module) are ignored.
In Schism 20230906 the Note-offs behave as expected throughout.

In keep_it_tight.mod, a C00 command is ignored.
- Open keep_it_tight.mod in Schism 20231029
- Press F5 to play the module
- Arrive at pattern order 9/41, Row 31
In Schism 20231029 the C00 command is ignored, and it does not break to the first row of the next pattern.
In Schism 20230906 the command behaves as expected.

There may still be more playback errors introduced with 20231029 that I have yet to encounter.

**Comment by mrpapersonic** [comment] 2024-01-17 22:18
winter_time_ii.xm *is* played as intended (IT also plays it like that). If you want true accuracy to FT2 use OpenMPT or 8bitbubsy's clone.

keep_it_tight.mod is performing an [extra](https://github.com/schismtracker/schismtracker/blob/cf58a82c74ae1daec60e158528315ed2e3a3eab8/player/effects.c#L1958) [check](https://github.com/8bitbubsy/it2play/blob/b351371356862fd776a41114a39ba241d9e4c4f1/it_m_eff.c#L471) that I just pushed a fix for.

I'm not entirely sure what I did to cause the NNA to fail in wb22-wk21.it...

**Comment by mrpapersonic** [comment] 2024-01-17 22:31
Hm... I can only replicate wb22-wk21.it in the Instrument List (although I'm on git master rather than 20231029).

https://github.com/schismtracker/schismtracker/assets/37962225/2ddb0ac1-b271-4bb0-820b-271d80fb353a

It doesn't seem to occur during playback.

**Comment by 0xHexaDecimator** [comment] 2024-01-18 22:17
> winter_time_ii.xm _is_ played as intended (IT also plays it like that). If you want true accuracy to FT2 use OpenMPT or 8bitbubsy's clone.

I don't have an install of IT handy to use as reference, so I tested it by having OpenMPT interpret it as an .it module. OpenMPT played it back as the older build of Schism did and did not make any changes regarding the note-offs for compatibility, so I assumed it a bug. Normally this works for me when I test modules that don't translate well with .it playback.

> Hm... I can only replicate wb22-wk21.it in the Instrument List (although I'm on git master rather than 20231029).
> It doesn't seem to occur during playback.

It works fine at pattern order 1/16 into 2/16 as you have in the clip, but at 3/16 into 4/16 (and some places elsewhere in the work) it behaves as in the instruments list. 

(oops, accidentally hit the close button instead of comment)

**Comment by mrpapersonic** [comment] 2024-01-18 22:31
> I don't have an install of IT handy to use as reference, so I tested it by having OpenMPT interpret it as an .it module. OpenMPT played it back as the older build of Schism did and did not make any changes regarding the note-offs for compatibility, so I assumed it a bug. Normally this works for me when I test modules that don't translate well with .it playback.

To replicate the behavior Schism (and IT) does, convert the XM to IT and then enable Old Effects and Compatible Gxx.
> It works fine at pattern order 1/16 into 2/16 as you have in the clip, but at 3/16 into 4/16 (and some places elsewhere in the work) it behaves as in the instruments list.

wtf... odd. I'll look into this along with #395.

**Comment by mrpapersonic** [comment] 2024-01-29 17:07
> It works fine at pattern order 1/16 into 2/16 as you have in the clip, but at 3/16 into 4/16 (and some places elsewhere in the work) it behaves as in the instruments list.

Both OpenMPT and IT 2.14 replicate Schism. This is not a bug, but since the piece was composed with Schism's prior playback routines (Schism 20220125) it no longer plays accurately.

In some time I'll see if I can send a patch to OpenMPT for detection of Schism <20231029 song compatibility.

**Comment by 0xHexaDecimator** [comment] 2024-01-30 03:21
Interesting! thanks

I know it played back in OpenMPT as it did in 'old' Schism at some point, but they must've fixed it recently as well as playback is consistent now. Also means XMPlay was playing it back correctly all along!
Was going to set up IT in DOSbox to check, but it seems DOSbox _still_ doesn't support MMX instructions for all of IT's features to work. 
Ah well, hope I didn't waste too much of your time with that!

**Closed as completed** 2024-01-30 04:01 UTC
