### ISSUE TITLE
Low tones do not sound clear.

### ISSUE THREAD

**Issue by DroidU** [schismtracker/schismtracker#264] opened 2021-06-10 17:10 UTC
If of music has very low instruments in it, they sound weak and noisy.

With this music you can clearly hear the bug on channel 5: https://www.hornet.org/music/songs/1997/n/no-tlove.zip

The same music on BeroTracker and the original Impulse Tracker sounds perfect.

**Comment by jangler** [comment] 2021-06-10 17:24
Does using a different mixing mode (Shift-F5 screen) fix your issue?

**Comment by DroidU** [comment] 2021-06-10 17:26
The problem occurs in all mixing modes.

**Comment by jangler** [comment] 2021-06-10 17:36
Looks like a duplicate of #27, let me know if I'm wrong and I'll reopen.

**Closed as completed by jangler** 2021-06-10 17:36 UTC
Labels: bug, duplicate
