### ISSUE TITLE
Buttons on instruments list getting stuck down

### ISSUE THREAD

**Issue by 0xHexaDecimator** [schismtracker/schismtracker#426] opened 2024-04-29 20:39 UTC
This has been around for seemingly forever, but when clicking through the envelope pages of the instrument list with the mouse cursor, some of the buttons get stuck down. They usually continue to stay down when coming over from other pages of the program, you can sometimes bring some of them back up if you continue to click them with the mouse cursor.
https://github.com/schismtracker/schismtracker/assets/151794548/1b802ae3-3ecf-499c-98bc-78348758f622
This only happens using the mouse cursor, navigating with the keyboard doesn't seem to do this. And it's also only these buttons.

**Comment by mrpapersonic** [comment] 2024-04-29 21:00
Dupe of #140

**Closed as not planned by mrpapersonic** 2024-04-29 21:00 UTC
